In [22]:
import pandas as pd

In [23]:
df_average_price = pd.read_csv('County_zhvi_uc_sfrcondo_tier_0.33_0.67_sm_sa_month.csv')
df_average_price = df_average_price[df_average_price['State'] == 'IL']
print('County_zhvi_uc_sfrcondo_tier_0.33_0.67_sm_sa_month.csv')
print(df_average_price.columns)
df_average_price.head()

County_zhvi_uc_sfrcondo_tier_0.33_0.67_sm_sa_month.csv
Index(['RegionID', 'SizeRank', 'RegionName', 'RegionType', 'StateName',
       'State', 'Metro', 'StateCodeFIPS', 'MunicipalCodeFIPS', '2000-01-31',
       ...
       '2023-07-31', '2023-08-31', '2023-09-30', '2023-10-31', '2023-11-30',
       '2023-12-31', '2024-01-31', '2024-02-29', '2024-03-31', '2024-04-30'],
      dtype='object', length=301)

,RegionID,SizeRank,RegionName,RegionType,StateName,State,Metro,StateCodeFIPS,MunicipalCodeFIPS,2000-01-31,...,2023-07-31,2023-08-31,2023-09-30,2023-10-31,2023-11-30,2023-12-31,2024-01-31,2024-02-29,2024-03-31,2024-04-30
1,139,1,Cook County,county,IL,IL,"Chicago-Naperville-Elgin, IL-IN-WI",17,31,148189.573478,...,289851.113537,292176.632577,294120.524613,295576.957386,296485.099881,296942.051291,297175.941476,298123.360542,300148.224126,302808.568850
58,1682,58,DuPage County,county,IL,IL,"Chicago-Naperville-Elgin, IL-IN-WI",17,43,197884.077325,...,376379.096956,379931.284697,382789.781475,385126.106336,386810.954009,388109.465169,389557.898099,392141.525262,395752.151848,399588.358047
91,220,91,Lake County,county,IL,IL,"Chicago-Naperville-Elgin, IL-IN-WI",17,97,180560.292126,...,332633.549459,335439.940437,337036.810694,337849.527398,338548.638354,339351.369693,340259.613549,341906.751761,344571.885976,347812.978189
97,330,97,Will County,county,IL,IL,"Chicago-Naperville-Elgin, IL-IN-WI",17,197,164570.033628,...,324805.679454,327169.555500,328370.905778,328953.423059,329629.160268,330300.122410,331338.195590,333008.268837,335700.003056,338863.798573
138,197,138,Kane County,county,IL,IL,"Chicago-Naperville-Elgin, IL-IN-WI",17,89,164141.632059,...,323651.152383,326422.821736,328438.627072,330228.160650,331407.673712,332391.869701,333434.435115,335152.137913,337857.433121,340802.554989

In [24]:
df_education = pd.read_csv('EducationReport.csv')
print('EducationReport.csv')
print(df_education.columns)
df_education.head()

EducationReport.csv
Index(['FIPS', 'Name', '2013 Rural-urban Continuum Code*', '1970', '1980',
       '1990', '2000', 'Unnamed: 7', '2008-2012', '2017-2021'],
      dtype='object')

,FIPS,Name,2013 Rural-urban Continuum Code*,1970,1980,1990,2000,Unnamed: 7,2008-2012,2017-2021
0,17001,"Adams, IL",5,7.2%,10.6%,13.7%,17.6%,NaN,21.0%,25.7%
1,17003,"Alexander, IL",3,3.4%,6.8%,7.8%,6.9%,NaN,8.9%,12.3%
2,17005,"Bond, IL",1,8.6%,11.2%,12.7%,15.0%,NaN,20.2%,21.2%
3,17007,"Boone, IL",2,7.3%,9.6%,12.0%,14.5%,NaN,19.9%,24.8%
4,17009,"Brown, IL",7,3.1%,7.7%,9.8%,9.2%,NaN,12.7%,13.0%

In [25]:
df_unemployment = pd.read_csv('UnemploymentReport.csv')
print('UnemploymentReport.csv')
print(df_unemployment.columns)
df_unemployment.head()

UnemploymentReport.csv
Index(['FIPS ', 'Name', '2014', '2015', '2016', '2017', '2018', '2019', '2020',
       '2021', '2022', 'Median Household Income (2021)', 'Unnamed: 12',
       '% of State Median HH Income'],
      dtype='object')

,FIPS,Name,2014,2015,2016,2017,2018,2019,2020,2021,2022,Median Household Income (2021),Unnamed: 12,% of State Median HH Income
0,17001,"Adams County, IL",5.4,5.0,4.8,3.9,3.8,3.3,6.4,4.0,3.3,"$59,777",NaN,82.8%
1,17003,"Alexander County, IL",10.8,9.2,9.3,8.4,8.2,6.1,10.3,8.1,6.3,"$41,816",NaN,57.9%
2,17005,"Bond County, IL",6.6,5.3,5.1,4.4,4.3,3.7,7.0,4.6,3.8,"$57,287",NaN,79.3%
3,17007,"Boone County, IL",7.9,6.5,6.4,6.7,5.7,5.4,11.4,8.7,6.4,"$71,557",NaN,99.1%
4,17009,"Brown County, IL",4.2,3.6,3.4,2.9,2.6,2.4,3.9,2.7,2.2,"$51,294",NaN,71.0%